import type { Metadata } from "next";
import "./globals.css";
import ControlsProvider from "@/providers/controls";
import Window from "@/components/three/Window";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`antialiased h-lvh`}>

        <ControlsProvider>
          <Window />
        </ControlsProvider>
        {children}

      </body>
    </html>
  );
}
